{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.blueprint
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.blueprint_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.blueprint/shiny.blueprint_{{ version }}.tar.gz
  sha256: 078483df67fea6416b09e49a3fdf2d1374eaa43fd0cafebf27a2fb7271040cbc

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-htmltools
    - r-shiny
    - r-shiny.react >=0.2.2
  run:
    - r-base
    - r-checkmate
    - r-htmltools
    - r-shiny
    - r-shiny.react >=0.2.2

test:
  commands:
    - $R -e "library('shiny.blueprint')"           # [not win]
    - "\"%R%\" -e \"library('shiny.blueprint')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shiny.blueprint
  license: LGPL-3.0-only
  summary: Easily use 'Blueprint', the popular 'React' library from Palantir, in your 'Shiny'
    app. 'Blueprint' provides a rich set of UI components for creating visually appealing
    applications and is optimized for building complex, data-dense web interfaces. This
    package provides most components from the underlying library, as well as special
    wrappers for some components to make it easy to use them in 'R' without writing
    'JavaScript' code.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
